[project]
name = "sc_be_contracts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["numpy>=2.3.2"]
[tool.hatch.build.targets.wheel]
packages = ["src/sc_be_contracts"]
