[project]
name = "sc-be-contracts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    "opencv-python>=4.11.0.86",
]
[tool.hatch.build.targets.wheel]
packages = ["src"]
